export interface City {
  name: string;
  slug: string;
}

export const NEPAL_CITIES: City[] = [
  { name: 'Kathmandu', slug: 'kathmandu' },
  { name: 'Pokhara', slug: 'pokhara' },
  { name: 'Lalitpur', slug: 'lalitpur' },
  { name: 'Bhaktapur', slug: 'bhaktapur' },
  { name: 'Biratnagar', slug: 'biratnagar' },
  { name: 'Birgunj', slug: 'birgunj' },
  { name: 'Bharatpur', slug: 'bharatpur' },
  { name: 'Butwal', slug: 'butwal' },
  { name: 'Dharan', slug: 'dharan' },
  { name: 'Hetauda', slug: 'hetauda' },
  { name: 'Janakpur', slug: 'janakpur' },
  { name: 'Nepalgunj', slug: 'nepalgunj' },
  { name: 'Dhangadhi', slug: 'dhangadhi' },
  { name: 'Itahari', slug: 'itahari' },
  { name: 'Damak', slug: 'damak' },
  { name: 'Tulsipur', slug: 'tulsipur' },
  { name: 'Ghorahi', slug: 'ghorahi' },
  { name: 'Siddharthanagar', slug: 'siddharthanagar' },
  { name: 'Kirtipur', slug: 'kirtipur' },
  { name: 'Lumbini', slug: 'lumbini' },
  { name: 'Tansen', slug: 'tansen' },
  { name: 'Gorkha', slug: 'gorkha' },
  { name: 'Damauli', slug: 'damauli' },
  { name: 'Baglung', slug: 'baglung' },
  { name: 'Ilam', slug: 'ilam' },
  { name: 'Dhankuta', slug: 'dhankuta' },
  { name: 'Rajbiraj', slug: 'rajbiraj' },
  { name: 'Lahan', slug: 'lahan' },
  { name: 'Gaur', slug: 'gaur' },
  { name: 'Kalaiya', slug: 'kalaiya' },
  { name: 'Mechinagar', slug: 'mechinagar' },
  { name: 'Banepa', slug: 'banepa' },
  { name: 'Dhulikhel', slug: 'dhulikhel' },
  { name: 'Thamel', slug: 'thamel' },
  { name: 'Patan', slug: 'patan' },
  { name: 'Namche Bazaar', slug: 'namche-bazaar' },
  { name: 'Lukla', slug: 'lukla' },
  { name: 'Chitwan', slug: 'chitwan' },
  { name: 'Manang', slug: 'manang' },
  { name: 'Mustang', slug: 'mustang' },
  { name: 'Jomsom', slug: 'jomsom' },
  { name: 'Nagarkot', slug: 'nagarkot' },
  { name: 'Bandipur', slug: 'bandipur' },
  { name: 'Daman', slug: 'daman' },
  { name: 'Besisahar', slug: 'besisahar' },
  { name: 'Tatopani', slug: 'tatopani' },
  { name: 'Jumla', slug: 'jumla' },
  { name: 'Surkhet', slug: 'surkhet' },
  { name: 'Dailekh', slug: 'dailekh' },
  { name: 'Darchula', slug: 'darchula' },
  { name: 'Mahendranagar', slug: 'mahendranagar' },
  { name: 'Tikapur', slug: 'tikapur' },
  { name: 'Bhadrapur', slug: 'bhadrapur' },
  { name: 'Birtamod', slug: 'birtamod' },
  { name: 'Inaruwa', slug: 'inaruwa' },
  { name: 'Charikot', slug: 'charikot' },
  { name: 'Bidur', slug: 'bidur' },
  { name: 'Malangwa', slug: 'malangwa' },
  { name: 'Lekhnath', slug: 'lekhnath' },
  { name: 'Waling', slug: 'waling' },
  { name: 'Palpa', slug: 'palpa' },
  { name: 'Kapilvastu', slug: 'kapilvastu' },
  { name: 'Dang', slug: 'dang' },
  { name: 'Bardiya', slug: 'bardiya' },
  { name: 'Solukhumbu', slug: 'solukhumbu' },
];
