/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import type { ImageConfig } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface Env {
  ASSETS: Fetcher;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

// Image security config. SVG sources with .svg extension auto-skip the
// optimization endpoint on the client side (served directly, no proxy).
// To route SVGs through the optimizer (with security headers), set
// dangerouslyAllowSVG: true in next.config.js and uncomment below:
// const imageConfig: ImageConfig = { dangerouslyAllowSVG: true };

// Paths whose GET responses are cached at the edge via Cache API.
// Workers run BEFORE the CDN cache, so Cache-Control headers alone
// do NOT make the CDN cache Worker-generated responses. The Cache API
// is required to explicitly store and serve cached responses.
// Ref: https://developers.cloudflare.com/cache/interaction-cloudflare-products/workers/
const CACHEABLE_API = ['/api/classifieds', '/api/jobs', '/api/events', '/api/lost-found', '/api/directory'];
const CACHE_TTL = 300; // 5 minutes

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Image optimization via Cloudflare Images binding.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      return handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
    }

    // Cache public GET API responses at the edge.
    // Only GET requests on public listing endpoints are cached.
    // POST/PATCH/DELETE always bypass cache.
    if (request.method === 'GET' && CACHEABLE_API.some(p => url.pathname.startsWith(p))) {
      const cache = caches.default;
      // Cache key uses URL only — exclude request headers (cookies, auth)
      // so all users share the same cached response for the same query.
      const cacheKey = new Request(url.toString());

      const cached = await cache.match(cacheKey);
      if (cached) return cached;

      const response = await handler.fetch(request, env, ctx);

      if (response.ok) {
        // Response constructor creates a mutable copy.
        const toCache = new Response(response.body, response);
        // s-maxage tells Cache API how long to keep it.
        toCache.headers.set('Cache-Control', `public, s-maxage=${CACHE_TTL}`);
        // Responses with Set-Cookie are never cached by the Cache API.
        toCache.headers.delete('Set-Cookie');
        // Store in cache without blocking the response.
        ctx.waitUntil(cache.put(cacheKey, toCache.clone()));
        return toCache;
      }

      return response;
    }

    // Everything else: SSR pages, auth API, POST endpoints, etc.
    // Wrap in try/catch so any thrown error (RSC render failures, DB errors,
    // etc.) is logged with full message + stack to Workers Logs *before*
    // React's RSC layer redacts it. Without this wrapper the actual cause
    // never reaches `wrangler tail` / observability — only the redacted
    // "An error occurred in the Server Components render" placeholder does.
    try {
      return await handler.fetch(request, env, ctx);
    } catch (err) {
      console.error('[worker] unhandled error', {
        url: url.toString(),
        method: request.method,
        message: err instanceof Error ? err.message : String(err),
        stack: err instanceof Error ? err.stack : undefined,
        digest: (err as { digest?: string })?.digest,
        name: err instanceof Error ? err.name : undefined,
      });
      throw err;
    }
  },

  // Cron (see wrangler.jsonc `triggers.crons`): refresh the daily-hub caches
  // (news RSS + forex/gold/AQI snapshot). Rather than importing the app's
  // data layer here (worker entry is bundled separately from the Next app,
  // so `@/` aliases don't resolve), we invoke our own API route in-process
  // with a synthetic request. The route authenticates via the JWT_SECRET
  // header so external callers can't trigger fetch storms.
  async scheduled(_controller: unknown, env: Env, ctx: ExecutionContext): Promise<void> {
    const secret = (env as unknown as { JWT_SECRET?: string }).JWT_SECRET;
    if (!secret) {
      console.error('[worker] scheduled: JWT_SECRET not bound, skipping refresh');
      return;
    }
    const request = new Request('https://onnepal.com/api/cron/refresh', {
      method: 'POST',
      headers: { 'x-cron-secret': secret },
    });
    try {
      const res = await handler.fetch(request, env, ctx);
      console.log('[worker] scheduled refresh →', res.status, await res.text());
    } catch (err) {
      console.error('[worker] scheduled refresh failed', err);
    }
  },
};
